apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - image: docker.io/library/springbooktk8s:0.0.1-SNAPSHOT
          name: springbooktk8s
          ports:
            - containerPort: 8080
          resources: {}