apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"springboot-demo","creationTimestamp":null,"labels":{"app":"springboot-demo"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"springboot-demo"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"springboot-demo"}},"spec":{"containers":[{"name":"springbooktk8s","image":"docker.io/library/springbooktk8s:0.0.1-SNAPSHOT","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: null
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-demo
    spec:
      containers:
        - image: docker.io/library/springbooktk8s:0.0.1-SNAPSHOT
          name: springbooktk8s
          resources: {}
status: {}